from __future__ import annotations

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
RUNTIME_CONFIG_PATH = ROOT / "static" / "runtime-config.js"

DEFAULTS = {
    "VITE_SUPABASE_URL": "",
    "VITE_SUPABASE_PUBLISHABLE_KEY": "",
    "VITE_SUPABASE_STORAGE_BUCKET": "garage-originals",
    "VITE_APP_TIMEZONE": "Asia/Hong_Kong",
}


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        values[key] = value
    return values


def js_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_config() -> dict[str, str]:
    file_values = parse_env_file(ENV_PATH)
    merged = {}
    for key, fallback in DEFAULTS.items():
        merged[key] = os.environ.get(key) or file_values.get(key) or fallback
    return merged


def write_runtime_config(config: dict[str, str]) -> None:
    content = f"""// Generated by scripts/sync_runtime_config.py
window.GaragePhotoWorkbenchConfig = {{
  supabaseUrl: "{js_escape(config['VITE_SUPABASE_URL'])}",
  supabasePublishableKey: "{js_escape(config['VITE_SUPABASE_PUBLISHABLE_KEY'])}",
  storageBucket: "{js_escape(config['VITE_SUPABASE_STORAGE_BUCKET'])}",
  timezone: "{js_escape(config['VITE_APP_TIMEZONE'])}",
}};
"""
    RUNTIME_CONFIG_PATH.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    write_runtime_config(build_config())
